//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUS_ACTIVITY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUS_ACTIVITY_TYPE()
        {
            this.CUS_ACTIVITY = new HashSet<CUS_ACTIVITY>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentTypeId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public bool IsFinal { get; set; }
        public bool OnlyFamilyCardHolder { get; set; }
        public bool IsBlocked { get; set; }
        public bool OnlyOneActivity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUS_ACTIVITY> CUS_ACTIVITY { get; set; }
    }
}
