//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_CUSTOMER()
        {
            this.CUS_TRANSACTION = new HashSet<CUS_TRANSACTION>();
            this.GEN_CUSTOMER_DOCUMENT = new HashSet<GEN_CUSTOMER_DOCUMENT>();
            this.SAL_INVOICE = new HashSet<SAL_INVOICE>();
            this.CUS_ESCORT = new HashSet<CUS_ESCORT>();
            this.CUS_FAMILY_CARD = new HashSet<CUS_FAMILY_CARD>();
            this.CUS_CHANGE_FUND = new HashSet<CUS_CHANGE_FUND>();
            this.CUS_CHANGE_FUND1 = new HashSet<CUS_CHANGE_FUND>();
        }
    
        public long CustomerId { get; set; }
        public Nullable<long> BoxNumber { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string InvoiceName { get; set; }
        public string Gender { get; set; }
        public string CivilNum { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CustomerStatus { get; set; }
        public string MemberNature { get; set; }
        public Nullable<int> SessionNumber { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> ReceiptVoucherNumber { get; set; }
        public Nullable<System.DateTime> ReceiptVoucherDate { get; set; }
        public int JoiningSharesCount { get; set; }
        public int SharesCount { get; set; }
        public bool CalculateEarnings { get; set; }
        public Nullable<int> BankId { get; set; }
        public bool PrintNameOnInv { get; set; }
        public bool RegisteredInMinistry { get; set; }
        public bool DataCompleted { get; set; }
        public string Notes { get; set; }
        public bool IsArchived { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUS_TRANSACTION> CUS_TRANSACTION { get; set; }
        public virtual GEN_CUSTOMER_ADDRESS GEN_CUSTOMER_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_CUSTOMER_DOCUMENT> GEN_CUSTOMER_DOCUMENT { get; set; }
        public virtual GEN_CUSTOMER_BANK GEN_CUSTOMER_BANK { get; set; }
        public virtual GEN_JOB GEN_JOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAL_INVOICE> SAL_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUS_ESCORT> CUS_ESCORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUS_FAMILY_CARD> CUS_FAMILY_CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUS_CHANGE_FUND> CUS_CHANGE_FUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUS_CHANGE_FUND> CUS_CHANGE_FUND1 { get; set; }
    }
}
