//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_SUPPLIER_TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_SUPPLIER_TRANSACTION()
        {
            this.GEN_SUPPLIER_NOT_ALLOWED_TRANS = new HashSet<GEN_SUPPLIER_NOT_ALLOWED_TRANS>();
        }
    
        public int SubTransId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_SUPPLIER_NOT_ALLOWED_TRANS> GEN_SUPPLIER_NOT_ALLOWED_TRANS { get; set; }
    }
}
