//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_SUPPLIER_DOCUMENT
    {
        public long DocumentId { get; set; }
        public Nullable<long> SupId { get; set; }
        public Nullable<long> TypeId { get; set; }
        public string DocName { get; set; }
        public string DocTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        public virtual GEN_SUPPLIER GEN_SUPPLIER { get; set; }
        public virtual LST_SUPPLIER_DOCUMENT_TYPE LST_SUPPLIER_DOCUMENT_TYPE { get; set; }
    }
}
