//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_ITEM()
        {
            this.GEN_ITEM_ALLOWED_TRANSACTION = new HashSet<GEN_ITEM_ALLOWED_TRANSACTION>();
            this.GEN_ITEM_GENERALIZATION = new HashSet<GEN_ITEM_GENERALIZATION>();
            this.GEN_ITEM_LOCATION = new HashSet<GEN_ITEM_LOCATION>();
            this.GEN_ITEM_UNIT = new HashSet<GEN_ITEM_UNIT>();
            this.INV_RECEIPT_DETAILS = new HashSet<INV_RECEIPT_DETAILS>();
            this.PUR_PROMOTION_DETAILS = new HashSet<PUR_PROMOTION_DETAILS>();
            this.PUR_PURCHASE_INV_DETAILS = new HashSet<PUR_PURCHASE_INV_DETAILS>();
        }
    
        public long ItemId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string EngName { get; set; }
        public string ItemStatus { get; set; }
        public string ItemReceiptType { get; set; }
        public string ItemType { get; set; }
        public string ItemTransactionType { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<long> SupId { get; set; }
        public Nullable<long> SupSectorId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<int> CommitteeNo { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<int> Factor { get; set; }
        public decimal MainCost { get; set; }
        public decimal Cost { get; set; }
        public decimal ConsumerProfitPerc { get; set; }
        public decimal WholesaleProfitPerc { get; set; }
        public decimal ConsumerDiscPerc { get; set; }
        public decimal WholesaleDiscPerc { get; set; }
        public decimal FreePerc { get; set; }
        public decimal DiscPerc { get; set; }
        public decimal MainPrice { get; set; }
        public decimal Price { get; set; }
        public decimal WholesalePrice { get; set; }
        public Nullable<int> QtyMin { get; set; }
        public Nullable<int> QtyMax { get; set; }
        public Nullable<decimal> PackageWeight { get; set; }
        public Nullable<long> PackageUnit { get; set; }
        public bool IsSpecialOffer { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public bool IsWeight { get; set; }
        public bool IsContainExpiryDate { get; set; }
        public bool IsSellNotAllow { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public string OldId { get; set; }
    
        public virtual GEN_BRAND GEN_BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_ITEM_ALLOWED_TRANSACTION> GEN_ITEM_ALLOWED_TRANSACTION { get; set; }
        public virtual GEN_ITEM_CATEGORY GEN_ITEM_CATEGORY { get; set; }
        public virtual GEN_SUPPLIER GEN_SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_ITEM_GENERALIZATION> GEN_ITEM_GENERALIZATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_ITEM_LOCATION> GEN_ITEM_LOCATION { get; set; }
        public virtual LST_COUNTRY LST_COUNTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_ITEM_UNIT> GEN_ITEM_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_RECEIPT_DETAILS> INV_RECEIPT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUR_PROMOTION_DETAILS> PUR_PROMOTION_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUR_PURCHASE_INV_DETAILS> PUR_PURCHASE_INV_DETAILS { get; set; }
    }
}
