//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_CUSTOMER_ADDRESS
    {
        public long CustomerId { get; set; }
        public string AutomtedNumber { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public Nullable<int> Floor { get; set; }
        public string AvenueNumber { get; set; }
        public string Plot { get; set; }
        public string MailBox { get; set; }
        public string PostalCode { get; set; }
        public string Employer { get; set; }
        public string Guardian { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MobileNumber { get; set; }
        public string MobileNumber2 { get; set; }
        public string WorkAddress { get; set; }
        public Nullable<int> KinshipId { get; set; }
    
        public virtual GEN_AREA GEN_AREA { get; set; }
        public virtual GEN_CUSTOMER GEN_CUSTOMER { get; set; }
        public virtual GEN_KINSHIP_TIES GEN_KINSHIP_TIES { get; set; }
        public virtual GEN_SECTION GEN_SECTION { get; set; }
    }
}
