//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_SUPPLIER_NOT_ALLOWED_TRANS
    {
        public long Id { get; set; }
        public long SupId { get; set; }
        public int SubTransId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        public virtual GEN_SUPPLIER GEN_SUPPLIER { get; set; }
        public virtual GEN_SUPPLIER_TRANSACTION GEN_SUPPLIER_TRANSACTION { get; set; }
    }
}
