//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_PROMOTION_DETAILS
    {
        public long DetailsId { get; set; }
        public Nullable<long> PromotionId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Factor { get; set; }
        public decimal MainCost { get; set; }
        public decimal MainPrice { get; set; }
        public decimal PromotionPrice { get; set; }
        public decimal NetDeffirence { get; set; }
        public decimal Qty { get; set; }
        public string Package { get; set; }
        public bool IsItemStoped { get; set; }
        public Nullable<long> StoppedItemBy { get; set; }
        public Nullable<System.DateTime> StoppedItemDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        public virtual GEN_ITEM GEN_ITEM { get; set; }
        public virtual PUR_PROMOTION PUR_PROMOTION { get; set; }
    }
}
