//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_PROMOTION_LOCATION
    {
        public long PromotionLocationId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> PromotionId { get; set; }
    
        public virtual GEN_LOCATION GEN_LOCATION { get; set; }
        public virtual PUR_PROMOTION PUR_PROMOTION { get; set; }
    }
}
