//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_PURCHASE_INV
    {
        public long PurchaseId { get; set; }
        public string InvNumber { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> SupId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderRecieveDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> EnterpriseDiscount { get; set; }
        public Nullable<decimal> CostAfterDiscount { get; set; }
        public Nullable<decimal> FreePercentage { get; set; }
        public Nullable<decimal> ConsumerDiscount { get; set; }
        public Nullable<decimal> CostNet { get; set; }
        public string InvType { get; set; }
        public string InvStatus { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        public virtual GEN_LOCATION GEN_LOCATION { get; set; }
        public virtual GEN_SUPPLIER GEN_SUPPLIER { get; set; }
    }
}
