//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL_INVOICE_DETAILS
    {
        public long DetailsId { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public string Barcode { get; set; }
        public Nullable<long> ItemUnitId { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        public virtual GEN_ITEM_UNIT GEN_ITEM_UNIT { get; set; }
        public virtual SAL_INVOICE SAL_INVOICE { get; set; }
    }
}
